Kritischer Fehler im Hauptprogramm
Exception: <built-in function add_image> returned a result with an exception set
Exception: 
Error:     [1001]
Command:   add_image
Item:      0 
Label:     Not found
Item Type: Unknown
Message:   Texture not found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\hendr\Documents\Programmieren\paperless_sort_low_quality_ollama\gui.py", line 486, in <module>
    dpg.add_image(
    ~~~~~~~~~~~~~^
        texture_tag="preview_texture",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        tag="preview_image",
        ^^^^^^^^^^^^^^^^^^^^
        show=False
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\hendr\AppData\Local\Programs\Python\Python313\Lib\site-packages\dearpygui\dearpygui.py", line 4855, in add_image
    return internal_dpg.add_image(texture_tag, label=label, user_data=user_data, use_internal_label=use_internal_label, tag=tag, width=width, height=height, indent=indent, parent=parent, before=before, source=source, payload_type=payload_type, drag_callback=drag_callback, drop_callback=drop_callback, show=show, pos=pos, filter_key=filter_key, tracked=tracked, track_offset=track_offset, tint_color=tint_color, border_color=border_color, uv_min=uv_min, uv_max=uv_max, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <built-in function add_image> returned a result with an exception set
